//
// Created by Shaul, Bar on 17/03/2022.
//

#ifndef AWS_ELASTICACHE_CLUSTER_CLIENT_LIBMEMCACHED_TLS_H
#define AWS_ELASTICACHE_CLUSTER_CLIENT_LIBMEMCACHED_TLS_H

#if defined(USE_TLS) && USE_TLS

#include <libmemcached-1.0/tls.h>




#endif //USE_TLS
#endif //AWS_ELASTICACHE_CLUSTER_CLIENT_LIBMEMCACHED_TLS_H
