//
// Created by Shaul, Bar on 30/03/2022.
//

#ifndef AWS_ELASTICACHE_CLUSTER_CLIENT_LIBMEMCACHED_TLS_H
#define AWS_ELASTICACHE_CLUSTER_CLIENT_LIBMEMCACHED_TLS_H


class tls {

};


#endif //AWS_ELASTICACHE_CLUSTER_CLIENT_LIBMEMCACHED_TLS_H
